name: CI/CD to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 542005048614.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t myflaskapprepo:latest .

      - name: Tag Docker Image
        run: |
          docker tag myflaskapprepo:latest 542005048614.dkr.ecr.ap-south-1.amazonaws.com/myflaskapprepo:latest

      - name: Push Docker Image
        run: |
          docker push 542005048614.dkr.ecr.ap-south-1.amazonaws.com/myflaskapprepo:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster my-ecs-cluster \
            --service my-ecs-service \
            --force-new-deployment
