name: CI/CD to ECS (EC2)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 542005048614.dkr.ecr.ap-south-1.amazonaws.com

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t myflaskapprepo:${IMAGE_TAG} .

      - name: Tag Docker Image
        run: docker tag myflaskapprepo:${IMAGE_TAG} 542005048614.dkr.ecr.ap-south-1.amazonaws.com/myflaskapprepo:${IMAGE_TAG}

      - name: Push Docker Image
        run: docker push 542005048614.dkr.ecr.ap-south-1.amazonaws.com/myflaskapprepo:${IMAGE_TAG}

      - name: Update ECS task definition with new image
        run: |
          jq '.containerDefinitions[0].image="542005048614.dkr.ecr.ap-south-1.amazonaws.com/myflaskapprepo:'${IMAGE_TAG}'"' ecs-task-def.json > ecs-task-def-updated.json
          aws ecs register-task-definition --cli-input-json file://ecs-task-def-updated.json

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster favorable-panda-ziqey2 \
            --service my-flask-service \
            --force-new-deployment
